# Generated by Django 4.2.3 on 2023-07-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='img', max_length=200, null=True),
        ),
    ]
