# Generated by Django 4.2.3 on 2023-07-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_image_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='BlogImage',
        ),
    ]
